/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPage;

import config.db_configuration;
import java.awt.Color;
import java.awt.print.PrinterException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import static jdk.nashorn.internal.objects.NativeString.search;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author SCC-COMLAB
 */
public class ORDER extends javax.swing.JInternalFrame {

    /**
     * Creates new form inventory
     */
    public ORDER() {
        initComponents();
        displayData();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
        
    }
    
    public void displayData(){
        try{
            db_configuration db = new db_configuration();
            ResultSet rs = db.getData("SELECT * FROM tbl_orderitem");
            
        }catch(SQLException ex){
            System.out.println("Errors: "+ex.getMessage());
        
        }
    }
    
    
   
    Color hovbtn = new Color(69,60,240);
    Color defbtn = new Color(126,120,240);
   
    public String action;
   
    public void close(){
        this.dispose();
        dashBoard df = new dashBoard();
        df.setVisible(true);
        ORDER up = new ORDER();
        df.maindesktop.add(up).setVisible(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        next = new javax.swing.JButton();
        quant = new javax.swing.JTextField();
        cashier_id = new javax.swing.JTextField();
        products = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        order_id = new javax.swing.JTextField();
        totalpayment = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        size = new javax.swing.JTextField();
        orderdatte = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        close1 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setAutoscrolls(true);
        jPanel1.setLayout(null);

        next.setBackground(new java.awt.Color(0, 102, 102));
        next.setText("NEXT");
        next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextMouseClicked(evt);
            }
        });
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next);
        next.setBounds(560, 360, 110, 40);

        quant.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantActionPerformed(evt);
            }
        });
        jPanel1.add(quant);
        quant.setBounds(520, 100, 220, 40);

        cashier_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cashier_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashier_idActionPerformed(evt);
            }
        });
        jPanel1.add(cashier_id);
        cashier_id.setBounds(110, 90, 220, 40);

        products.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choco", "Mocha", "Strawberry", "Vanilla" }));
        products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsActionPerformed(evt);
            }
        });
        jPanel1.add(products);
        products.setBounds(110, 200, 220, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CASHIER ID:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 90, 100, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("TOTAL PAYMENT:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(390, 250, 130, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("ORDER ID:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 150, 90, 40);

        order_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        order_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                order_idActionPerformed(evt);
            }
        });
        jPanel1.add(order_id);
        order_id.setBounds(110, 150, 220, 40);

        totalpayment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalpayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalpaymentActionPerformed(evt);
            }
        });
        jPanel1.add(totalpayment);
        totalpayment.setBounds(520, 260, 220, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("PRODUCTS:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 200, 90, 40);

        size.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        size.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeActionPerformed(evt);
            }
        });
        jPanel1.add(size);
        size.setBounds(110, 250, 220, 40);

        orderdatte.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        orderdatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderdatteActionPerformed(evt);
            }
        });
        jPanel1.add(orderdatte);
        orderdatte.setBounds(520, 160, 220, 40);

        price.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        jPanel1.add(price);
        price.setBounds(520, 210, 220, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("SIZE:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 260, 90, 40);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setAutoscrolls(true);
        jPanel2.setLayout(null);

        close1.setBackground(new java.awt.Color(0, 102, 102));
        close1.setText("CLOSE");
        close1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close1MouseClicked(evt);
            }
        });
        close1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close1ActionPerformed(evt);
            }
        });
        jPanel2.add(close1);
        close1.setBounds(620, 420, 110, 40);

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField8);
        jTextField8.setBounds(520, 70, 220, 40);

        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField9);
        jTextField9.setBounds(130, 70, 220, 40);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choco", "Mocha", "Strawberry", "Vanilla" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(130, 170, 220, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("CASHIER ID:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 70, 100, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("SIZE:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(410, 70, 100, 50);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("ORDER ID:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 120, 90, 40);

        jTextField10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField10);
        jTextField10.setBounds(130, 120, 220, 40);

        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField11);
        jTextField11.setBounds(520, 230, 220, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("PRODUCTS:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(30, 170, 90, 40);

        jTextField12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField12);
        jTextField12.setBounds(130, 220, 220, 40);

        jTextField13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField13);
        jTextField13.setBounds(520, 120, 220, 40);

        jTextField14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField14);
        jTextField14.setBounds(520, 170, 220, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("SIZE:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(30, 220, 90, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 0, 0);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("QUANTITY:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(410, 90, 100, 50);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("ORDER DATE:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(400, 150, 100, 50);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("PRICE:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(410, 200, 70, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseClicked
      OrderItem or = new OrderItem();
      or.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_nextMouseClicked

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed

        if (products.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Please select your Products!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } 
        
        
        if (size.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please type your size", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }else if(quant.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please type your Quantity!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }else if(orderdatte.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please type your order date!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }else if(price.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please type your Price!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }else if(totalpayment.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please type your Total Payment", "Error", JOptionPane.ERROR_MESSAGE);
            return;

        } 
    }//GEN-LAST:event_nextActionPerformed

    private void quantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantActionPerformed
    
    }//GEN-LAST:event_quantActionPerformed

    private void productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productsActionPerformed

    private void cashier_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashier_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashier_idActionPerformed

    private void order_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_order_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_order_idActionPerformed

    private void totalpaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalpaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalpaymentActionPerformed

    private void sizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sizeActionPerformed

    private void orderdatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderdatteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderdatteActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void close1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_close1MouseClicked

    private void close1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_close1ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cashier_id;
    private javax.swing.JButton close1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton next;
    private javax.swing.JTextField order_id;
    private javax.swing.JTextField orderdatte;
    private javax.swing.JTextField price;
    private javax.swing.JComboBox<String> products;
    private javax.swing.JTextField quant;
    private javax.swing.JTextField size;
    private javax.swing.JTextField totalpayment;
    // End of variables declaration//GEN-END:variables
}
